### ISSUE TITLE
内测需求

### ISSUE THREAD

**Issue by bingshilei** [PyQt5/PyQtClient#1]
1、如果没有案例，可以弹出提示；
2、左侧控件字体较小，不直观；
3、有些控件代码，点击弹出“could not find or load the Qt platform plugin "windows"”

**Comment by bingshilei** [comment]
1、QLabel图片不加载显示；
2、左边导航栏代码文件建议单击显示代码。
3、右侧详细界面，代码没有办法复制

**Comment by 892768447** [comment]
增加了
1、单击显示代码
2、代码复制
3、左侧字体加粗
