### ISSUE TITLE
Does it support 64-bit systems?

### ISSUE THREAD

**Issue by SindreYang** [PyQt5/PyQtClient#6]
Installing qtwebkit is painful, but I want to run it on Linux!

**Comment by 892768447** [comment]
Compiling and test pyqt qtwebkit，It will take some time.

**Comment by 892768447** [comment]
1. Install Python35+
2. Install Qt5.13.1 to ~/Qt5.13.1
3. clone https://github.com/PyQt5/PyQtWebKit and run ./build.sh
