### ISSUE TITLE
打包成exe过程遇到问题

### ISSUE THREAD

**Issue by PvauLy** [PyQt5/PyQtClient#7]
你好，打扰一下，我在打包源代码成exe文件时遇到了如下报错问题，可以帮忙看下吗，耽误您的时间了。谢谢您
![EHKSY@C@HP{J J_GFKG%Y_T](https://user-images.githubusercontent.com/44231931/64608566-8dc20480-d3fd-11e9-85f9-5e311a11f652.png)
![%PI8A31F64S9W)@OV`A6%YB](https://user-images.githubusercontent.com/44231931/64608575-93b7e580-d3fd-11e9-8424-bf0754b7da78.png)
![129IB7K GY_OP}HZ )7K`1U](https://user-images.githubusercontent.com/44231931/64608591-99153000-d3fd-11e9-978e-b624facfb8a3.png)

**Comment by 892768447** [comment]
这是py2exe的问题。你可以 下载已经打包好的 https://github.com/PyQt5/PyQtClient/releases 软件。。只需要更新Library.zip就可以替换功能

**Comment by PvauLy** [comment]
好的，明白，非常感谢您的回复
