### ISSUE TITLE
右边窗口创建了浏览器打开网页遇到超链接无法跳转（点击无效）

### ISSUE THREAD

**Issue by PvauLy** [PyQt5/PyQtClient#8]
你好，我在使用过程中遇到了一个问题：窗口网页无法跳转问题，需要设置新的标签页面去解决吗还是有什么好的办法呢，或者是有什么demo吗，求大神指点。（ QtWebEngineWidgets.QWebEngineView）

**Comment by 892768447** [comment]
提供简单的测试代码

**Comment by PvauLy** [comment]
（PyQt5/PyQtClient）在您源代码程序的基础上，我增加了使用浏览器打开网页（位置如右图红框），
![image](https://user-images.githubusercontent.com/44231931/64916737-9cba0580-d7b5-11e9-920d-1fd84e36d976.png)，但一些超链接无法跳转

**Comment by 892768447** [comment]
参考：https://github.com/PyQt5/PyQtClient/blob/master/Utils/NetworkAccessManager.py

我对请求做了拦截

**Comment by PvauLy** [comment]
非常感谢大佬的回复。原来是这样，学习了，谢谢您。



------------------ 原始邮件 ------------------
发件人: "ヽoo悾絔℅o。"<notifications@github.com>; 
发送时间: 2019年9月15日(星期天) 晚上10:01
收件人: "PyQt5/PyQtClient"<PyQtClient@noreply.github.com>; 
抄送: "Trust"<1261541333@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [PyQt5/PyQtClient] 右边窗口创建了浏览器打开网页遇到超链接无法跳转（点击无效） (#8)




参考：https://github.com/PyQt5/PyQtClient/blob/master/Utils/NetworkAccessManager.py
 
我对请求做了拦截
